"""Where a user action came from (rec-spec §4.3, ADR-0015).

One shared, optional, typed shape — deliberately *not* six loose fields
redeclared per endpoint, which is how the same six columns end up spelled
five slightly different ways across an API.

Every field is optional and every combination is valid. An action taken
from a non-recommendation surface carries no `recommendation_request_id`,
and an action taken from a bookmarked URL carries nothing at all; both are
complete records, not degraded ones. ADR-0015: "Never infer attribution
that is not known."

This is a Pydantic model rather than a dataclass-plus-schema pair because
it is genuinely one thing: the request body embeds it, the service takes it,
and the repository reads it. A second near-identical domain type would only
create a conversion step that can drift.
"""

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class InteractionSurface(StrEnum):
    """Where in the product an action originated.

    A closed set, not free text, even though ``interaction_events.surface``
    is a plain TEXT column. This data feeds offline model training
    (ADR-0015), where a typo'd surface is not a harmless string — it is a
    silently-wrong row that no constraint would ever catch. Adding a
    surface later is one line here plus a regenerated client.

    ``HOME``/``SHELF``/``SIMILAR`` intentionally use the same string values
    as ``recommendations.surfaces.Surface`` so an event's ``surface`` can be
    compared directly against ``recommendation_requests.surface`` without a
    translation table. The remaining values name surfaces that have no
    recommendation batch behind them at all.
    """

    HOME = "home"
    SHELF = "shelf"
    SIMILAR = "similar"
    SEARCH = "search"
    BOOK_DETAIL = "book_detail"
    SHELF_BOOKS = "shelf_books"
    RATED = "rated"


class TasteSeedSource(StrEnum):
    """Where a taste seed was selected (ADR-0019). Closed at the API edge
    for the same reason as :class:`InteractionSurface` — this is training
    evidence, and an unvalidated free-text origin is a row nobody can
    interpret later."""

    ONBOARDING = "onboarding"


class InteractionAttribution(BaseModel):
    """Optional provenance attached to an interaction write.

    Frozen: attribution describes something that already happened by the
    time it reaches a service, so nothing downstream should be rewriting it
    mid-request.
    """

    model_config = ConfigDict(frozen=True)

    surface: InteractionSurface | None = None
    #: Short-lived *browsing* session (rec-spec §4.1), generated by the
    #: frontend per tab and rotated on inactivity. Never the 30-day auth
    #: session `sid` — ADR-0015 explains why conflating the two is a
    #: security-adjacent mistake, not just a modelling one.
    session_id: UUID | None = None
    recommendation_request_id: UUID | None = None
    search_query_id: UUID | None = None
    #: The book whose page the action was taken *from* (e.g. a save made
    #: from another book's "Similar books" strip), not the book acted on.
    source_book_id: int | None = None
    #: 0-based position within the surface that produced it, matching
    #: `recommendation_results.position` and `RecommendationBookItem.rank`.
    rank_position: int | None = Field(default=None, ge=0)


NO_ATTRIBUTION = InteractionAttribution()
"""Explicit "origin unknown", so callers that genuinely have nothing to say
don't each invent their own empty instance."""
