"""catalog search indexes

Revision ID: 43bc30e307a2
Revises: 21d1bf300e2a
Create Date: 2026-08-04 22:05:00.000000

Trigram (title, author) and full-text (description) indexes (spec §8.3:
"title/author trigram; full-text search"). Hand-written, not autogenerated —
these are expression/opclass indexes SQLAlchemy's ORM layer doesn't model.
The search endpoint itself is a later phase; this only prepares the indexes
it will need.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43bc30e307a2"
down_revision: str | Sequence[str] | None = "21d1bf300e2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE INDEX ix_books_title_trgm ON books USING gin (title gin_trgm_ops)")
    op.execute(
        "CREATE INDEX ix_books_primary_author_name_trgm "
        "ON books USING gin (primary_author_name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_books_description_fts "
        "ON books USING gin (to_tsvector('english', coalesce(description, '')))"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_books_description_fts")
    op.execute("DROP INDEX IF EXISTS ix_books_primary_author_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_books_title_trgm")
